In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets, svm, metrics

In [8]:
from sklearn.datasets import load_digits
digits = load_digits()
train = digits.data
targets = digits.target

In [9]:
from sklearn.cluster import AffinityPropagation

ap = AffinityPropagation(preference = -50000, damping=0.8, random_state=0)
pred = ap.fit(train)

In [10]:
# print(targets)
Labels = pred.labels_
print(Labels)

[3 6 6 ... 6 9 6]


In [11]:
def clusterChecking(tar,lab):
    new_lab=np.copy(lab)
    for j in range(10):
        temp=np.where(lab==j)
        temp_array=tar[temp]
        vals,counts = np.unique(temp_array, return_counts=True)
       
        index = np.argmax(counts)
        m=vals[index]
        new_lab[temp]=m
    return new_lab  

In [12]:
new = clusterChecking(targets, Labels)
# print(targets)
print(Labels)
print(new)

[3 6 6 ... 6 9 6]
[0 8 8 ... 8 9 8]


In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(targets, new)
print(cm)

[[175   0   0   0   2   0   1   0   0   0]
 [  0  55  25   2   0   0   1   0  99   0]
 [  2   1 136   3   0   0   0   3  24   8]
 [  1   0   0 147   0   2   0  10   7  16]
 [  0   4   0   0 161   1   0   7   8   0]
 [  2   0   0   0   1 157   1   0   3  18]
 [  1   0   0   0   1   1 174   0   3   1]
 [  0   0   0   0   3   1   0 168   7   0]
 [  2   6   4  21   0   6   0   2 128   5]
 [  8  17   0  12   0   7   0   6   2 128]]


In [14]:
accuracy = metrics.fowlkes_mallows_score(targets, new)
print('Accuracy: ',accuracy*100, '%')

Accuracy:  68.5334082194355 %
